# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

# Auto-unlock gnome-keyring with empty password (for autologin)
exec-once = echo '' | gnome-keyring-daemon --unlock

# Throne - autostart in tray (window rule keeps it on hidden workspace)
exec-once = /home/shafty/Programms/Throne/Throne

# Ayugram - autostart minimized to tray
exec-once = AyuGram -startintray

