# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1

# Throne - start on hidden special workspace (tray only)
windowrule = match:class ^(Throne)$, workspace special silent

# AyuGram/Telegram Mini Apps - float freely
windowrule = match:title ^(Mini App:.*)$, float on
windowrule = match:title ^(Mini App:.*)$, center on

